### ISSUE TITLE
Improved CITATION formatting

### ISSUE THREAD

**Issue by zeileis** [markvanderloo/extremevalues#5]
Mark,

together with the CRAN team we are currently discussing strategies for better checking of `CITATION` files. In a CRAN screening, the `extremevalues` package stood out due to its frequent use of `citFooter()` in its [CITATION file](https://github.com/markvanderloo/extremevalues/blob/master/cran/inst/CITATION).

I think it would be better to set up a `CITATION` with two `bibentry()` objects as shown below. Or is there a particular reason why the second citation is in the footer only?

I'm happy to turn this into a PR if you would prefer that.

Thanks for your consideration & best wishes,
Achim

```
if(!exists("meta") || is.null(meta)) meta <- packageDescription("extremevalues")
year <- sub("-.*", "", meta$Date)
note <- sprintf("R package version %s", meta$Version)

bibentry(bibtype = "Manual",
         title   = "extremevalues: Univariate Outlier Detection",
         author  = person(given = "Mark", family = "van der Loo"),
         year    = year,
         note    = note,
	 url     = "https://CRAN.R-project.org/package=extremevalues",
	 header  = "To cite extremevalues in publications use:"
)

bibentry(bibtype = "TechReport",
         title   = "Distribution Based Outlier Detection for Univariate Data",
         author  = person(given = "Mark", family = "van der Loo"),
         institution = "Statistics Netherlands",
         number  = "10003",
         address = "The Hague",
         url     = "https://www.cbs.nl/",
         year    = "2010",
         header  = "To cite the underlying theory, please use:"
)
```

**Comment by markvanderloo** [comment]
Hi Achim, thanks for this! I have no idea why the package has this `CITATION` format. It probably seemed like a good idea at the time :). Will fix.

**Comment by zeileis** [comment]
:nerd_face: I know that feeling... Thanks in advance for the fix!
